name: naslet
description: NaSlet

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_simple_dependency_injection: ^2.0.0
  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.1
  dio: ^4.0.6
  google_sign_in: ^5.4.3
  flutter_login_vk: ^2.2.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  shared_preferences: ^2.0.16
  dropdown_button2: ^1.9.2
  gradient_borders: ^0.2.0
  yandex_mapkit: ^3.2.0
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.2.0
  flutter_staggered_grid_view: ^0.6.2

flutter_icons:
  image_path_android: "assets/icons/app_icon/icon.png"
  image_path_ios: "assets/icons/app_icon/icon.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/icons/app_icon/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"

dependency_overrides:
  args: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/profile_page/
    - assets/icons/nav_bar_icons/
    - assets/icons/profile_page/
    - assets/icons/card_icon/
    - assets/icons/details_page/
    - assets/icons/events_page/
    - assets/images/map/
    - assets/icons/map/
    - assets/icons/app_icon/

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: fonts/Inter/Inter-Thin.ttf
          weight: 100

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logoSplash.png

flutter_intl:
  main_locale: ru
  enabled: true